import { STIX_Two_Text } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';

const stixTwoText = STIX_Two_Text({
  variable: '--font-stix-two-text',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${stixTwoText.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col md:max-w-2xl mx-auto w-full bg-white dark:bg-neutral-900 md:pb-42 pb-16">
        <ThemeProvider defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
