import { Geist, Geist_Mono, STIX_Two_Text } from "next/font/google";
import "./globals.css";

const stixTwoText = STIX_Two_Text({
  variable: "--font-stix-two-text",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${stixTwoText.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="mx-auto w-full md:max-w-2xl mt-8 md:mt-24">
          {children}
        </div>
      </body>
    </html>
  );
}
